name: Run GPT Task

on: [push]

jobs:
  run-gpt-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: poetry install

      - name: Run GPT Task
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use the secret
        run: poetry run python run_gpt_task.py
